import { Achievement, LevelDefinition, QuestDefinition, SideQuestDefinition, UserProfile, WeightEntry } from '../types';

export const OFFICIAL_BASELINE_DATE = '2026-09-03';
export const OFFICIAL_BASELINE_WEIGHT = 242.2;
export const OFFICIAL_START_DATE = '2026-09-06';
export const OFFICIAL_GOAL_DATE = '2026-12-01';
export const OFFICIAL_GOAL_WEIGHT = 220.0;
export const TOTAL_ARC_DAYS = 87;

export const DEFAULT_PROFILE: UserProfile = {
  name: 'Champion',
  hasStartedArc: false,
  startDate: OFFICIAL_START_DATE,
  goalDate: OFFICIAL_GOAL_DATE,
  startingWeight: OFFICIAL_BASELINE_WEIGHT,
  goalWeight: OFFICIAL_GOAL_WEIGHT,
  baselineDate: OFFICIAL_BASELINE_DATE,
  dailyXpGoal: 100,
  dailyStepGoal: 10000,
  soundEffects: true,
  hapticFeedback: true,
};

export const INITIAL_WEIGHT_ENTRY: WeightEntry = {
  id: 'baseline-weight',
  date: OFFICIAL_BASELINE_DATE,
  weight: OFFICIAL_BASELINE_WEIGHT,
  note: 'Official Winter Arc Weight Baseline',
  createdAt: '2026-09-03T08:00:00.000Z',
};

// Exactly 19 Daily Quests in Exact Chronological Order
export const DAILY_QUESTS: QuestDefinition[] = [
  {
    id: 'morning_prayer',
    order: 1,
    title: 'Morning Prayer',
    type: 'boolean',
    baseXp: 15,
    category: 'mindset',
    description: 'Dedicate the start of the day in prayer and gratitude.',
  },
  {
    id: 'water_checkpoint_1',
    order: 2,
    title: 'Drink Water — Checkpoint 1',
    type: 'boolean',
    baseXp: 2,
    category: 'nutrition',
    description: 'First 16-20oz glass upon waking to rehydrate.',
  },
  {
    id: 'take_creatine',
    order: 3,
    title: 'Take Creatine',
    type: 'boolean',
    baseXp: 5,
    category: 'nutrition',
    description: 'Daily 5g dose for muscle power and recovery.',
  },
  {
    id: 'drink_energy_drink',
    order: 4,
    title: 'Drink Energy Drink',
    type: 'boolean',
    baseXp: 0, // Tracked, awards 0 XP
    category: 'routine',
    description: 'Track caffeine intake (awards 0 XP).',
  },
  {
    id: 'hit_the_gym',
    order: 5,
    title: 'Hit the Gym',
    type: 'boolean',
    baseXp: 15,
    category: 'fitness',
    description: 'Heavy lifting or dedicated training session.',
  },
  {
    id: 'water_checkpoint_2',
    order: 6,
    title: 'Drink Water — Checkpoint 2',
    type: 'boolean',
    baseXp: 2,
    category: 'nutrition',
    description: 'Post-workout hydration boost.',
  },
  {
    id: 'eat_breakfast',
    order: 7,
    title: 'Eat Breakfast',
    type: 'boolean',
    baseXp: 5,
    category: 'nutrition',
    description: 'High protein breakfast to fuel metabolism.',
  },
  {
    id: 'water_checkpoint_3',
    order: 8,
    title: 'Drink Water — Checkpoint 3',
    type: 'boolean',
    baseXp: 2,
    category: 'nutrition',
    description: 'Mid-morning hydration checkpoint.',
  },
  {
    id: 'shower_get_ready',
    order: 9,
    title: 'Shower / Get Ready',
    type: 'boolean',
    baseXp: 3,
    category: 'hygiene',
    description: 'Freshen up, groomed and locked in.',
  },
  {
    id: 'make_protein_coffee',
    order: 10,
    title: 'Make Protein Coffee',
    type: 'boolean',
    baseXp: 5,
    category: 'nutrition',
    description: 'Sip delicious protein-infused brew.',
  },
  {
    id: 'go_to_school_work',
    order: 11,
    title: 'Go to School / Work',
    type: 'boolean',
    baseXp: 5,
    category: 'routine',
    description: 'Show up on time and locked in on obligations.',
  },
  {
    id: 'eat_healthy_lunch',
    order: 12,
    title: 'Eat Healthy Lunch',
    type: 'boolean',
    baseXp: 7,
    category: 'nutrition',
    description: 'Clean whole foods meal within macros.',
  },
  {
    id: 'water_checkpoint_4',
    order: 13,
    title: 'Drink Water — Checkpoint 4',
    type: 'boolean',
    baseXp: 2,
    category: 'nutrition',
    description: 'Afternoon hydration checkpoint.',
  },
  {
    id: 'daily_focus',
    order: 14,
    title: 'Daily Focus',
    type: 'focus', // 1-5 selector
    baseXp: 0, // Calculated dynamically from 1-5
    category: 'mindset',
    description: 'Rate your focus & productivity: 1 to 5.',
  },
  {
    id: 'water_checkpoint_5',
    order: 15,
    title: 'Drink Water — Checkpoint 5',
    type: 'boolean',
    baseXp: 2,
    category: 'nutrition',
    description: 'Evening hydration goal completed.',
  },
  {
    id: 'prepare_for_tomorrow',
    order: 16,
    title: 'Prepare for Tomorrow',
    type: 'boolean',
    baseXp: 5,
    category: 'routine',
    description: 'Lay out clothes, gym bag, and plan tomorrow.',
  },
  {
    id: 'evening_prayer',
    order: 17,
    title: 'Evening Prayer',
    type: 'boolean',
    baseXp: 15,
    category: 'mindset',
    description: 'Give thanks, reflect on the day, and seek peace.',
  },
  {
    id: 'steps',
    order: 18,
    title: 'Steps',
    type: 'numeric',
    baseXp: 0, // Calculated dynamically
    category: 'fitness',
    description: 'Input exact step count. 10k goal.',
  },
  {
    id: 'sleep',
    order: 19,
    title: 'Sleep',
    type: 'numeric',
    baseXp: 0, // Calculated dynamically
    category: 'recovery',
    description: 'Input actual hours slept last night.',
  },
];

// Exactly 7 Established Side Quests (Bonus Only)
export const SIDE_QUESTS: SideQuestDefinition[] = [
  {
    id: 'no_pornography',
    order: 1,
    title: 'No Pornography',
    xp: 10,
    description: 'Complete discipline over dopamine pathways and mind.',
  },
  {
    id: 'screen_time_under_5h',
    order: 2,
    title: 'Recreational Screen Time Under 5 Hours',
    xp: 8,
    description: 'Recreational/nonessential usage under 5 hours (work/school excluded).',
  },
  {
    id: 'comfort_zone',
    order: 3,
    title: 'Get Out of Your Comfort Zone',
    xp: 7,
    description: 'Do something uncomfortable that fosters character growth.',
  },
  {
    id: 'extra_study_reading',
    order: 4,
    title: 'Extra Study / Reading — 30+ Minutes',
    xp: 5,
    description: 'Intentional Bible study, reading, or skill development beyond requirements.',
  },
  {
    id: 'reset_the_base',
    order: 5,
    title: 'Reset the Base',
    xp: 5,
    description: 'Clean or organize something meaningful: room, desk, car, or workspace.',
  },
  {
    id: 'serve_encourage',
    order: 6,
    title: 'Serve / Encourage Someone',
    xp: 5,
    description: 'Intentionally help, serve, encourage, or do something thoughtful.',
  },
  {
    id: 'do_the_thing',
    order: 7,
    title: 'Do the Thing',
    xp: 7,
    description: 'Finish a critical task you have been avoiding or procrastinating on.',
  },
];

// Focus XP Mapping
export const FOCUS_XP_MAP: Record<number, { xp: number; label: string }> = {
  1: { xp: 0, label: 'Wasted the day' },
  2: { xp: 2, label: 'Below average' },
  3: { xp: 4, label: 'Solid' },
  4: { xp: 6, label: 'Very productive' },
  5: { xp: 8, label: 'Locked in' },
};

// 20 Level Progression Curve calibrated for 87-day Winter Arc (approx 100-120 XP/day)
export const LEVELS: LevelDefinition[] = [
  { level: 1, title: 'INITIATE', xpRequired: 0 },
  { level: 2, title: 'STARTER', xpRequired: 150 },
  { level: 3, title: 'RECRUIT', xpRequired: 350 },
  { level: 4, title: 'DISCIPLINED', xpRequired: 650 },
  { level: 5, title: 'CONSISTENT', xpRequired: 1050 },
  { level: 6, title: 'FOCUSED', xpRequired: 1550 },
  { level: 7, title: 'COMMITTED', xpRequired: 2150 },
  { level: 8, title: 'LOCKED IN', xpRequired: 2850 },
  { level: 9, title: 'RELENTLESS', xpRequired: 3650 },
  { level: 10, title: 'UNSTOPPABLE', xpRequired: 4550 },
  { level: 11, title: 'IRONCLAD', xpRequired: 5550 },
  { level: 12, title: 'ASCENDANT', xpRequired: 6650 },
  { level: 13, title: 'JUGGERNAUT', xpRequired: 7850 },
  { level: 14, title: 'CHAMPION', xpRequired: 9150 },
  { level: 15, title: 'MASTER', xpRequired: 10550 },
  { level: 16, title: 'PARAGON', xpRequired: 12050 },
  { level: 17, title: 'TITAN', xpRequired: 13650 },
  { level: 18, title: 'MYTHIC', xpRequired: 15350 },
  { level: 19, title: 'IMMORTAL', xpRequired: 17150 },
  { level: 20, title: 'WINTER GOD', xpRequired: 19000 },
];

export const INITIAL_ACHIEVEMENTS: Achievement[] = [
  {
    id: 'first_blood',
    title: 'FIRST BLOOD',
    description: 'Complete your first Winter Arc day.',
    category: 'streak',
    icon: 'Sword',
  },
  {
    id: 'were_balling',
    title: "WE'RE BALLING",
    description: 'Earn 100+ XP in one day.',
    category: 'xp',
    icon: 'Sparkles',
  },
  {
    id: 'locked_in_day',
    title: 'LOCKED IN',
    description: 'Earn 120+ XP in one day.',
    category: 'xp',
    icon: 'Flame',
  },
  {
    id: 'hat_trick',
    title: 'HAT TRICK',
    description: '3 successful days in a row.',
    category: 'streak',
    icon: 'Trophy',
  },
  {
    id: 'seven_days_strong',
    title: 'SEVEN DAYS STRONG',
    description: '7 successful days in a row.',
    category: 'streak',
    icon: 'Zap',
  },
  {
    id: 'unstoppable',
    title: 'UNSTOPPABLE',
    description: '14 successful days in a row.',
    category: 'streak',
    icon: 'ShieldAlert',
  },
  {
    id: 'touch_grass',
    title: 'TOUCH GRASS',
    description: 'Complete the Screen Time Side Quest.',
    category: 'discipline',
    icon: 'Trees',
  },
  {
    id: '10k_club',
    title: '10K CLUB',
    description: 'Reach 10,000 steps in one day.',
    category: 'fitness',
    icon: 'Footprints',
  },
  {
    id: 'walker',
    title: 'WALKER',
    description: 'Accumulate 100,000 total steps.',
    category: 'fitness',
    icon: 'Compass',
  },
  {
    id: 'gym_rat',
    title: 'GYM RAT',
    description: 'Complete 20 gym sessions.',
    category: 'fitness',
    icon: 'Dumbbell',
  },
  {
    id: 'prayer_warrior',
    title: 'PRAYER WARRIOR',
    description: 'Complete both Morning and Evening Prayer for 7 consecutive days.',
    category: 'habit',
    icon: 'Sun',
  },
  {
    id: 'book_of_life',
    title: 'BOOK OF LIFE',
    description: 'Complete Extra Study / Reading side quest 10 times.',
    category: 'habit',
    icon: 'BookOpen',
  },
  {
    id: 'down_five',
    title: 'DOWN FIVE',
    description: 'Reach 237.2 lb or lower.',
    category: 'weight',
    icon: 'TrendingDown',
  },
  {
    id: 'down_ten',
    title: 'DOWN TEN',
    description: 'Reach 232.2 lb or lower.',
    category: 'weight',
    icon: 'Award',
  },
  {
    id: 'goal_crusher',
    title: 'GOAL CRUSHER',
    description: 'Reach 220 lb or lower.',
    category: 'weight',
    icon: 'Crown',
  },
  {
    id: 'hydration_master',
    title: 'HYDRATION MASTER',
    description: 'Complete all 5 water checkpoints in a single day.',
    category: 'habit',
    icon: 'Droplets',
  },
  {
    id: 'deep_sleep',
    title: 'DEEP RECOVERY',
    description: 'Log 8.0+ hours of sleep on 5 different days.',
    category: 'habit',
    icon: 'Moon',
  },
  {
    id: 'centurion',
    title: 'CENTURION',
    description: 'Reach Level 5 (Consistent) in character progression.',
    category: 'xp',
    icon: 'Shield',
  },
  {
    id: 'overdrive_king',
    title: 'OVERDRIVE KING',
    description: 'Achieve 120+ XP on 5 different days.',
    category: 'xp',
    icon: 'Target',
  },
  {
    id: 'clean_slate',
    title: 'CLEAN SLATE',
    description: 'Complete "Reset the Base" 5 times.',
    category: 'discipline',
    icon: 'Sparkle',
  },
  {
    id: 'laser_focus',
    title: 'LASER FOCUS',
    description: 'Rate daily focus as 5 (Locked In) 7 times.',
    category: 'discipline',
    icon: 'Crosshair',
  },
  {
    id: 'creatine_machine',
    title: 'CREATINE MACHINE',
    description: 'Take creatine on 14 different days.',
    category: 'habit',
    icon: 'Pill',
  },
];
